name: build

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Restore go cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16.x
    - name: Set up kubebuilder
      uses: fluxcd/pkg/actions/kubebuilder@main
    - name: Run tests
      run: make test
      env:
        KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
    - name: Build container image
      run: make docker-build IMG=ghcr.io/fluxcd/${{ github.event.repository.name }}:latest
      env:
        KUBEBUILDER_ASSETS: ${{ github.workspace }}/kubebuilder/bin
